// vueApp/src/views/HomePage.vue
<template>
  <div class="home-container">
    <div class="login-container">
      <h1>FastAPI Backend</h1>
      <p>Vue.js + TypeScript 프론트엔드와 FastAPI 백엔드로 구성된 애플리케이션입니다.</p>
      
      <div v-if="loading" class="loading">로딩 중...</div>
      <div v-else-if="error" class="error">오류: {{ error }}</div>
      <div v-else class="login-button-container">
        <GoogleLogin
          v-if="googleClientId"
          :callback="handleGoogleLogin"
          :error-callback="handleGoogleError"
          prompt
        />
        <p class="login-description">Google 계정으로 로그인하세요</p>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from 'vue'
import { useAuthStore } from '../stores/authStore'
import { decodeCredential } from 'vue3-google-login'

export default defineComponent({
  name: 'HomePage',
  setup() {
    const authStore = useAuthStore()
    const googleClientId = ref<string | null>(null)
    const loading = ref(true)
    const error = ref<string | null>(null)

    onMounted(async () => {
      try {
        const clientId = await authStore.fetchGoogleClientId()
        googleClientId.value = clientId
        loading.value = false
      } catch (err) {
        error.value = 'Google 클라이언트 ID를 가져오는데 실패했습니다.'
        loading.value = false
      }
    })

    const handleGoogleLogin = async (response: any) => {
      try {
        // Google 응답에서 사용자 정보 추출
        const userData = decodeCredential(response.credential)
        
        // 백엔드에 로그인 요청
        const loginData = {
          name: userData.name,
          email: userData.email,
          imageUrl: userData.picture
        }
        
        await authStore.googleLogin(loginData)
        alert('로그인 성공!')
      } catch (err) {
        console.error('Google 로그인 오류:', err)
        error.value = 'Google 로그인에 실패했습니다.'
      }
    }

    const handleGoogleError = () => {
      error.value = 'Google 로그인에 실패했습니다.'
    }

    return {
      googleClientId,
      loading,
      error,
      handleGoogleLogin,
      handleGoogleError
    }
  }
})
</script>

<style scoped>
.home-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  padding: 20px;
}

.login-container {
  background-color: white;
  border-radius: 8px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  padding: 30px;
  width: 100%;
  max-width: 500px;
  text-align: center;
}

h1 {
  color: #333;
  margin-bottom: 10px;
}

p {
  color: #666;
  margin-bottom: 30px;
}

.login-button-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 20px;
}

.login-description {
  margin-top: 15px;
  font-size: 14px;
  color: #666;
}

.loading, .error {
  padding: 20px;
  border-radius: 4px;
  margin: 20px 0;
}

.loading {
  background-color: #e8f4fd;
  color: #0277bd;
}

.error {
  background-color: #ffebee;
  color: #c62828;
}
</style>

// frontend/src/components/pages/HomePage.tsx
import React, { useEffect, useState } from 'react';
import { observer } from 'mobx-react-lite';
import './HomePage.css';
import { GoogleLogin } from '@react-oauth/google';
import { GoogleOAuthProvider } from '@react-oauth/google';
import rootStore from '../../stores/rootStore';

const HomePage: React.FC = () => {
  const { authStore } = rootStore;
  const [googleClientId, setGoogleClientId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchGoogleClientId = async () => {
      try {
        const clientId = await authStore.fetchGoogleClientId();
        setGoogleClientId(clientId);
        setLoading(false);
      } catch (err) {
        setError('Google 클라이언트 ID를 가져오는데 실패했습니다.');
        setLoading(false);
      }
    };

    fetchGoogleClientId();
  }, [authStore]);

  const handleGoogleLogin = async (credentialResponse: any) => {
    try {
      // Google 응답에서 ID 토큰 추출
      const idToken = credentialResponse.credential;
      
      // ID 토큰을 디코딩하여 사용자 정보 추출
      const base64Url = idToken.split('.')[1];
      const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
      const jsonPayload = decodeURIComponent(atob(base64).split('').map(function(c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
      }).join(''));
      
      const { name, email, picture } = JSON.parse(jsonPayload);
      
      // 백엔드에 로그인 요청
      const userData = {
        name,
        email,
        imageUrl: picture
      };
      
      const response = await fetch('http://localhost:8000/users/google-login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(userData),
        credentials: 'include'
      });
      
      if (!response.ok) {
        throw new Error('로그인 처리 중 오류가 발생했습니다.');
      }
      
      const data = await response.json();
      
      // 로그인 성공 처리
      localStorage.setItem('access_token', data.tokens.access_token);
      localStorage.setItem('refresh_token', data.tokens.refresh_token);
      
      // 사용자 정보 저장
      authStore.user = data.user;
      authStore.isAuthenticated = true;
      
      alert('로그인 성공!');
      
    } catch (err) {
      console.error('Google 로그인 오류:', err);
      setError('Google 로그인에 실패했습니다.');
    }
  };

  if (loading) {
    return <div className="home-container"><div className="login-container">로딩 중...</div></div>;
  }

  if (error) {
    return <div className="home-container"><div className="login-container">오류: {error}</div></div>;
  }

  return (
    <div className="home-container">
      <div className="login-container">
        <h1>FastAPI Backend</h1>
        <p>React + TypeScript 프론트엔드와 FastAPI 백엔드로 구성된 애플리케이션입니다.</p>
        
        {googleClientId ? (
          <GoogleOAuthProvider clientId={googleClientId}>
            <div className="login-button-container">
              <GoogleLogin
                onSuccess={handleGoogleLogin}
                onError={() => setError('Google 로그인에 실패했습니다.')}
                useOneTap
              />
              <p className="login-description">Google 계정으로 로그인하세요</p>
            </div>
          </GoogleOAuthProvider>
        ) : (
          <div>Google 클라이언트 ID를 가져오는데 실패했습니다.</div>
        )}
      </div>
    </div>
  );
};

export default observer(HomePage);
